### PR TITLE
Add MyBB hover style + font color for buttons

### PR DESCRIPTION
**Pull request by Eldenroot**
I just left the original background color, MyBB uses this one

background: #eee url(/images/buttons_bg.png) repeat-x;

### CODE REVIEW

**Review by Eldenroot — COMMENTED** [review]
.myreactions-container padding

**Review by Eldenroot — COMMENTED** [review]
Align myreactions-container

**Comment by Eldenroot** [comment]
Here is the result:
small changes

**Comment by MattRogowski** [comment]
Thank you, does look nicer like that 👍

**Comment by Eldenroot** [comment]
You are welcome! Glad to help

**Pull request merged**
